#ifndef SILEXARS_SYSTEM_MANAGEMENT_MANAGERS_DEVICEMANAGERS_DEVICEMANAGERS_H
#define SILEXARS_SYSTEM_MANAGEMENT_MANAGERS_DEVICEMANAGERS_DEVICEMANAGERS_H

#include "GraphicsManager.h"
#include "NetworkManager.h"
#include "SensorManager.h"

#endif // DEVICEMANAGERS_H
